### ISSUE TITLE
Fix typo in the wiki regarding `-webide-parse-mode`

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct_webide#102]
The wiki says twice incorrectly ~`-webide-parsing-mode`~ instead of **`-webide-parse-mode`** in this section: https://github.com/kaitai-io/kaitai_struct_webide/wiki/Features#eager-instance-parsing.

I thought that I'll be able to open a pull request for it, but it turns out I'm not, because the Wiki section on GitHub works somehow weird.

**Comment by koczkatamas** [comment]
Fixed. Thanks for the report!
