### ISSUE TITLE
Types of lazy instances are not shown

### ISSUE THREAD

**Issue by DarkDimius** [kaitai-io/kaitai_struct_webide#12]
https://gist.github.com/DarkDimius/9c8e32c9912d294600aa1d875cdb52d1 - ksy 
https://yadi.sk/d/JkoqyX2A3ENycN - binary
https://yadi.sk/i/DZC3t9yc3EP6Xg - screenshot

quoting @koczkatamas 
> yeah, it's a bug (or a missing feature), what happens here is that the 'decoded' property is an instance, so I don't know the type of it only after processing (expanding) it, but after doing that I don't modify the node anymore, only add child nodes

**Comment by koczkatamas** [comment]
I could not test on your ksy because it did not compile for me.

Currently you can test it out on https://ide.kaitai.io/devel/ .

If the issue is not solved fully please reopen the issue.
