### ISSUE TITLE
UTF-16LE strings and UTF-16BE are not printed in the object tree panel

### ISSUE THREAD

**Issue by humdogm** [kaitai-io/kaitai_struct_webide#131]
In the converter panel it displays UTF-16LE and UTF-16BE strings just fine.

In the object tree panel items of type UTF-16LE and UTF-16BE show up as �.

**Comment by KOLANICH** [comment]
Without a spec and a file and some describtion what you mean (the address of the problematic node in the tree and the offset of the data, maybe even a screenshot) it is hard to understand what you mean. Because the last time I worked with the formats using UTF-16 in the WebIDE, it worked fine for me.

**Comment by humdogm** [comment]
The gpt file is what I'm trying to parse, it's not really a text file.
[gpt_entries.txt](https://github.com/kaitai-io/kaitai_struct_webide/files/7193978/gpt_entries.txt)

Here is the ksy file I defined:
[gpt_entry.ksy.txt](https://github.com/kaitai-io/kaitai_struct_webide/files/7193984/gpt_entry.ksy.txt)

This is what I see in the web ui:
![image](https://user-images.githubusercontent.com/6947043/133964662-b7724119-7687-4f40-b036-cfe7116dc0b4.png)
![image](https://user-images.githubusercontent.com/6947043/133964704-d7707678-474f-41a1-9169-45108bfb81a2.png)

**Comment by KOLANICH** [comment]
The screenshot shows the string is little endian, but in your spec it is written `UTF-16BE`

**Comment by humdogm** [comment]
In either case, it should not show as � anyway, it should show either of "ssd" or those chinese characters seen in the converter panel.

**Comment by humdogm** [comment]
Why is the converter panel able to show a useful string for UTF-16BE then?

**Comment by KOLANICH** [comment]
>Why is the converter panel able to show a useful string for UTF-16BE then?

On the screenshot you have provided the useful string is for `UTF-16LE`, not `UTF-16BE`.

**Comment by humdogm** [comment]
It also didn't work when using UTF-16LE.

Figured out the problem, UTF-16 can't use strz, should probably throw an error if using strz and multi-byte encodings instead of showing �.

Though the UEFI spec says that the name should be human readable and be a null-terminated string, I guess these are non-standard partition entry names.

**Comment by dgelessus** [comment]
> Figured out the problem, UTF-16 can't use strz

Yep, this is a known bug - see kaitai-io/kaitai_struct#187. I'll close this issue as a duplicate then (please comment if I overlooked something)
