### ISSUE TITLE
Ability to create link to IDE with custom urls for format specification and binary file

### ISSUE THREAD

**Issue by underhood** [kaitai-io/kaitai_struct_webide#153]
I would like to have a button on my repo that says sth. like open_this_in_web_ide where I will add `ksy` file and binary file as parameters. E.g. link like `https://ide.kaitai.io/index?format_url=github.com/repo/file.ksy&binary_file=github.com/repo/sample_binary.bin`

Is something like that possible?

**Comment by GreyCat** [comment]
Just to make sure I understood the request correctly: the expectation is that Web IDE would fetch two requested URLs and make use of format spec + binary file? What about CORS/origin policies?

**Comment by generalmimon** [comment]
Duplicate of https://github.com/kaitai-io/kaitai_struct_webide/issues/124
