### ISSUE TITLE
Feature request: although parsing has failed, show all the parsed tree till the fail

### ISSUE THREAD

**Issue by svecol** [kaitai-io/kaitai_struct_webide#156]
When iteratively writing a kaitai description for some complicated file format, sometimes parsing fails after you add some code. But you can't really see how it failed: you get EOF message in the error window and the object tree window shows the last successful parsing. 
It would be very helpful if in such situations the object tree showed all it managed to parse (even if it is a wrong parsing), so that you could scroll through the object tree and see what might has caused the problem.

And thank you for creating this amazing tool!

**Comment by sem-geologist** [comment]
I agree this is one of these annoyances of this rather outstanding tool. It needs special techniques when used for reverse engineering. For this problem, I normally increasingly comment out structs, until it parses. It a bit tedious but works to find the cause where the parsing derails.

**Comment by svecol** [comment]
So I've come up with a hack that allows IDE to do what I wanted. But I don't propose a commit to this rep, as it shouldn't be implemented this way. So I give a working example in a fork: https://github.com/svecol/kaitai_struct_webide .
Now if parsing fails, the object tree shows all that was possible to be parsed plus an error indicating key in the very bottom of the tree.
The way it works is that in the debug version of js parser the body of the read function of the root class gets enveloped with try-catch construction, which prevents getting error. So implementing it properly I think would require changes both to kaitai_struct_compiler and kaitai_struct_webide, none of which I'm capable of.
