### ISSUE TITLE
3rd party licensing page missing in deployment

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct_webide#28]
About box has a link to https://ide.kaitai.io/LICENSE-3RD-PARTY.txt — which is 404 now. Probably something's not built and/or deployed properly in our CI deployment process.

**Comment by koczkatamas** [comment]
Fixed on devel with https://github.com/kaitai-io/kaitai_struct_webide/commit/c681c1e1a87f1c05b128cbe879c24fe035ed75d4 and on production with https://github.com/kaitai-io/kaitai_struct_webide/commit/cdc7ef06edd81d4de7bdfa1f6c90e4559f7ac34f

**Comment by GreyCat** [comment]
Confirming, it works now! Thanks!
