### ISSUE TITLE
Manual update

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_webide#44]
It is damn slow when I enter a char and it tries to compile an invalid ksy and parse a large file with it. It's better to compile and parse by ctrl+enter.

**Comment by koczkatamas** [comment]
It only compiles if you don't press any key for 500ms, but yeah, a manual compile mode is definitely a good idea!

**Comment by koczkatamas** [comment]
Please use https://ide.kaitai.io/devel/?noAutoCompile and press "Ctrl+Enter" in the .ksy editor to trigger recompilation manually.

**Comment by KOLANICH** [comment]
Thank you. But I guess having some GUI is better than params in URI.

**Comment by koczkatamas** [comment]
https://github.com/kaitai-io/kaitai_struct_webide/pulls ;)
