### ISSUE TITLE
Int behavior appears to be different on IDE

### ISSUE THREAD

**Issue by dcliftreaves** [kaitai-io/kaitai_struct_webide#57]
In my testing it appears that ints are locked at 32 bits. Also, stranger, is that shifting seems to be a rotation not a normal shift. 

I was trying to take 2 uint bytes and 4 uint bytes and, in an instance, shift the 2 byte value by 32 bits and add it to the 4 byte value. I then noticed odd behavior that indicated 32 bit int was the max supported and my shifts were just wrapping the 32 bits. Very unexpected. 

I thought perhaps I just didn't understand instances but then I noticed this example that is very similar to what I was doing:
http://formats.kaitai.io/vlq_base128_be/

My guess would be testing that on binary data that encodes values over 32 bits would expose this issue.

Tested on chrome on osx 10.12.6

**Comment by GreyCat** [comment]
This is a known problem which stems from JavaScript having no proper 64-bit integers support: http://doc.kaitai.io/lang_javascript.html

I suggest to continue discussion in https://github.com/kaitai-io/kaitai_struct/issues/183
