### ISSUE TITLE
YAML parser does not parse hex expressions correctly

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct_webide#63]
If we use `size: 0x30150-0x30010` then it becomes `this._io.readBytes(3304172224528);`.

The problem is probably the YAML parser thinks the expression is a hex number and parse it incorrectly. `3304172224528` = `0x30150030010` which is not `0x30150-0x30010` of course!

**Comment by GreyCat** [comment]
Another finding: `0b10101010` gets parsed as 0 by old YAML parser.

Fortunately, new parser introduced in https://ide.kaitai.io/devel/ works properly.
