### ISSUE TITLE
[FR] object tree: export to file

### ISSUE THREAD

**Issue by ildar** [kaitai-io/kaitai_struct_webide#65]
It'd be nice to export what I see in Object tree to a (YAML) file

**Comment by GreyCat** [comment]
I reckon that there's already option to export object tree (or fragment of it) into JSON:

![image](https://user-images.githubusercontent.com/157154/38625560-a876698a-3da2-11e8-9876-4b2d56c4c786.png)

**Comment by ildar** [comment]
Ahh!

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by ildar** [comment]
indeed, what I need. A few minor issues:
1. actually the `export to JSON` label is placed wrong: one can find it
only if look for it or inspects the whole UI.
2. The Object Tree doesn't have path to export: no context menu, nothing
close enough
3. just a side note: `export to JSON (hex)` does not produce a lawful JSON,
problem with hex, see
https://www.tutorialspoint.com/json/json_data_types.htm

Thanks! closing.
