### ISSUE TITLE
when I upload a disk image whose size is 525M the Kaitai Web IDE not response

### ISSUE THREAD

**Issue by ShiChaoYuatSH** [kaitai-io/kaitai_struct_webide#67]
when I upload a disk image whose size is 525M the Kaitai Web IDE not response.
when I uplaod the image to "https://ide.kaitai.io/#" the IDE not response, I build the IDE locally and the issue is the same, could you please tell me how should I do to parse a big image.

**Comment by koczkatamas** [comment]
Currently it's not possible to parse too big files with the WebIDE, but you can try to visualizer (ksv): https://github.com/kaitai-io/kaitai_struct_visualizer

But depending on your `.ksy` file, ksv may still parse your whole file which can make it also slow.
