### ISSUE TITLE
Error using reference, works with literal

### ISSUE THREAD

**Issue by slickriptide** [kaitai-io/kaitai_struct_webide#70]
Hello, Kaitai folks. I've fiddled with this every which way but loose and it looks like a bug in either Kaitai or the WebIDE.

Let's start with a picture:
![geobin_ksy](https://user-images.githubusercontent.com/13685009/44668288-d31dba80-a9d1-11e8-8c6f-80bb69541d65.jpg)

The explanations:
Code Window - This snippet of code:
`  root_def_group:
    seq:
      - id: group_size
        type: u4
      - id: group_name_len
        type: u2
      - id: group_name_val
        size: 35`

Hex Viewer: the string specified by group_name_val is highlighted. Just prior to it you can see the values of group_name_len and group_size likewise highlighted. 

Object Tree: The values above (and others) appear as specified, and the value of group_name_len is, in fact, 35. So far, so good.

If I now replace 'size: 35' with 'size: group_name_len', Kaitai barfs and produces the following errors: `Parse error: undefined
Call stack: undefined KaitaiEOFError: requested 12656 bytes, but only 194 bytes available`

Whatever's going on, isn't actually about group_name_len, specifically. If I delete group_size entirely from the spec, then the rest of root_def_group loads normally (though with bad values because it's loading from the wrong position).

If I treat this block of data as a block of bytes, I can load the entire file, so it's not really a problem with the data itself or the streaming/substreaming of the individual records. "Undefined" doesn't really help me figure out what it wants defined.

I can supply the ksy file and the data file that I'm reading.

**Comment by slickriptide** [comment]
Yes, it appears that I got hung up on the word "Undefined" and I should have investigated further. I've traced the problem to incorrect alignment/byte-padding in my string  processing. So, chalk this up to user error.

**Comment by GreyCat** [comment]
I agree that WebIDE error reporting can use a facelift to be little clearer. If you're proficient with JavaScript/TypeScript, would you care to contribute?
