### ISSUE TITLE
Wiki images need explicit heights set so deep-linking can work

### ISSUE THREAD

**Issue by brunchboy** [kaitai-io/kaitai_struct_webide#73]
First, let me thank you for an unbelievable tool, it has saved me countless hours already in the few days since I’ve found it, and I’m excited about it as a long-term platform for documenting sharing the progress of my reverse-engineering efforts.

At one point, @GreyCat wanted to call my attention to an opportunity to provide better context in the WebIDE by adding annotations to my `.ksy` file, and he linked me to 
https://github.com/kaitai-io/kaitai_struct_webide/wiki/Features#webide-representation

Unfortunately, that link scrolled to completely the wrong place, so it took me a while to find what he was trying to show me. The reason is that the images in the markdown for the wiki are missing their height attributes, so the browser initially renders a page without them, and as they fill in, scrolls to the wrong place, far away from the content I was supposed to see. I used to have the same problems with my own GitHub manuals, but fixed it by adding explicit height (and width) information to the markdown (or in my case, mostly asciidoc). Here is an example of a deep link into one of my image-heavy pages that stably scrolls to the right place now: https://github.com/Deep-Symmetry/beat-link-trigger/blob/master/doc/Players.adoc#loading-playing

I tried to edit the wiki to fix this, but apparently it is not open for contributions like that, hence this issue. Thanks again for such an amazing tool!

**Comment by generalmimon** [comment]
In fact, I did exactly this last month (https://github.com/kaitai-io/kaitai_struct_webide/wiki/Features/_compare/9b47a827bb31e151eb681b35cd8e35488e0687aa...62c675b13c1880d2aadb5894b741dbf09363e349) without knowing this issue exists, so it can be closed now :)
