### ISSUE TITLE
Update kaitai_struct_compiler to use with kaitai_struct_webide 

### ISSUE THREAD

**Issue by jaroslaw-wieczorek** [kaitai-io/kaitai_struct_webide#90]
How to use the latest version of the compiler from kaitai_struct_webide ?  I want to use version 0.9, but I can't find information on how to connect it. 
```yaml
  ks-version: 0.9
```
```bash
Parse error: undefined
Call stack: undefined io.kaitai.struct.format.YAMLParseException: /meta: this ksy requires compiler version at least 0.9, but you have 0.8
```

**Comment by GreyCat** [comment]
The same way you install the rest of the software on your system, e.g. install it using a packet manager or download archive with updated version and install it manually.

Most likely instructions you're looking for are available at http://kaitai.io/ => Download => choose your OS => "development (unstable) build".

**Comment by generalmimon** [comment]
Resolved with https://github.com/kaitai-io/kaitai_struct/issues/573, so this issue can be closed.

**Comment by GreyCat** [comment]
Clarifying that difference between https://ide.kaitai.io/ and https://ide.kaitai.io/devel still stands.
